# Generated by Django 4.2.14 on 2024-08-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HellotWorld',
            new_name='HelloWorld',
        ),
    ]
